# Generated by Django 5.0 on 2024-10-23 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastlogin",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 23, 7, 27, 58, 753802)
            ),
        ),
    ]
