# Generated by Django 5.0 on 2024-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_lastlogin_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastlogin",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
