# Generated by Django 5.1.2 on 2024-10-21 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 21, 17, 11, 35, 814621)
            ),
        ),
    ]
