# Generated by Django 5.0 on 2024-10-23 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="sales",
            name="amount_bought",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sales",
            name="amount_paid",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sales",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="goods",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pos.otherproducts",
            ),
        ),
    ]
