# Generated by Django 5.0 on 2024-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_sales_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
