# Generated by Django 5.0 on 2024-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_otherproducts_alter_sales_amount_bought_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="Product",
            field=models.CharField(default="Product", max_length=20),
        ),
        migrations.DeleteModel(
            name="OtherSales",
        ),
    ]
